package report

import (
	"bytes"
	"fmt"
	"html"
	"html/template"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// BuildBaseFilename returns a stable base filename for report artefacts.
func BuildBaseFilename(focus string, now time.Time) string {
	sanitized := sanitizeFocus(focus)
	return fmt.Sprintf("report_%s_%s", sanitized, now.Format("20060102_150405"))
}

// SaveMarkdown writes the markdown report to disk.
func SaveMarkdown(path string, report string) error {
	if err := os.WriteFile(path, []byte(report), 0o644); err != nil {
		return fmt.Errorf("write markdown report: %w", err)
	}
	return nil
}

// SaveHTML converts markdown into HTML and writes a full HTML report page.
func SaveHTML(path string, title string, markdown string) error {
	htmlDoc, err := RenderHTML(title, markdown)
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, htmlDoc, 0o644); err != nil {
		return fmt.Errorf("write html report: %w", err)
	}
	return nil
}

// RenderHTML converts a markdown subset to semantic HTML and wraps it in a styled document.
func RenderHTML(title string, markdown string) ([]byte, error) {
	content := markdownToHTML(markdown)

	tmpl := template.Must(template.New("report").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}}</title>
<style>
:root {
  color-scheme: dark;
  --bg: #0f1115;
  --fg: #e5e7eb;
  --muted: #9ca3af;
  --card: #151922;
  --accent: #60a5fa;
}
body {
  margin: 0;
  font-family: Inter, Segoe UI, Roboto, Arial, sans-serif;
  background: var(--bg);
  color: var(--fg);
  line-height: 1.55;
}
main {
  max-width: 860px;
  margin: 0 auto;
  padding: 2rem 1rem 4rem;
}
article {
  background: var(--card);
  border: 1px solid #1f2937;
  border-radius: 14px;
  padding: 1.25rem;
}
a { color: var(--accent); }
code, pre {
  background: #0b0e13;
  border-radius: 8px;
}
pre {
  padding: 0.85rem;
  overflow-x: auto;
}
small {
  color: var(--muted);
}
</style>
</head>
<body>
<main>
  <h1>{{.Title}}</h1>
  <small>Generated by KAE</small>
  <article>{{.Content}}</article>
</main>
</body>
</html>`))

	var out bytes.Buffer
	data := struct {
		Title   string
		Content template.HTML
	}{
		Title:   title,
		Content: template.HTML(content),
	}
	if err := tmpl.Execute(&out, data); err != nil {
		return nil, fmt.Errorf("render html template: %w", err)
	}
	return out.Bytes(), nil
}

// ArtifactPaths returns markdown/html report paths for a base filename.
func ArtifactPaths(base string) (markdownPath, htmlPath string) {
	return filepath.Clean(base + ".md"), filepath.Clean(base + ".html")
}

func sanitizeFocus(focus string) string {
	focus = strings.TrimSpace(strings.ToLower(focus))
	if focus == "" {
		return "kae"
	}
	var b strings.Builder
	for _, r := range focus {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_':
			b.WriteRune(r)
		case r == ' ' || r == '-':
			b.WriteRune('_')
		}
	}
	if b.Len() == 0 {
		return "kae"
	}
	return b.String()
}

func markdownToHTML(markdown string) string {
	lines := strings.Split(markdown, "\n")
	var out strings.Builder
	inList := false
	inCode := false

	closeList := func() {
		if inList {
			out.WriteString("</ul>\n")
			inList = false
		}
	}

	for _, raw := range lines {
		line := strings.TrimRight(raw, "\r")
		trim := strings.TrimSpace(line)

		if strings.HasPrefix(trim, "```") {
			closeList()
			if inCode {
				out.WriteString("</code></pre>\n")
				inCode = false
			} else {
				out.WriteString("<pre><code>")
				inCode = true
			}
			continue
		}

		if inCode {
			out.WriteString(html.EscapeString(line))
			out.WriteString("\n")
			continue
		}

		if trim == "" {
			closeList()
			continue
		}

		escaped := html.EscapeString(trim)
		switch {
		case strings.HasPrefix(trim, "### "):
			closeList()
			out.WriteString("<h3>" + html.EscapeString(strings.TrimSpace(trim[4:])) + "</h3>\n")
		case strings.HasPrefix(trim, "## "):
			closeList()
			out.WriteString("<h2>" + html.EscapeString(strings.TrimSpace(trim[3:])) + "</h2>\n")
		case strings.HasPrefix(trim, "# "):
			closeList()
			out.WriteString("<h1>" + html.EscapeString(strings.TrimSpace(trim[2:])) + "</h1>\n")
		case strings.HasPrefix(trim, "- "):
			if !inList {
				out.WriteString("<ul>\n")
				inList = true
			}
			out.WriteString("<li>" + html.EscapeString(strings.TrimSpace(trim[2:])) + "</li>\n")
		default:
			closeList()
			out.WriteString("<p>" + escaped + "</p>\n")
		}
	}
	closeList()
	if inCode {
		out.WriteString("</code></pre>\n")
	}
	return out.String()
}
